version: '3.8'

services:
  zookeeper:
    image: bitnami/zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka
    depends_on:
      - zookeeper
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  discovery:
    build: ../service-discovery
    ports:
      - "8761:8761"

  gateway:
    build: ../api-gateway
    ports:
      - "8080:8080"

  product-service:
    build: ../product-service
    depends_on:
      - kafka
      - mysql